// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ryliu.book.domain;

import com.ryliu.book.domain.BookTransaction;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BookTransaction_Roo_Configurable {
    
    declare @type: BookTransaction: @Configurable;
    
}
